#! /bin/sh
#
# This script is a filter to clenaup C files:
#  - Trailing spaces are removed.
#  - Unix-like end of line markers are used (LF).
#  - Code is re-indent.
#

## AStyle options:
options="--options=none --mode=c --preserve-date --quiet \
  --style=stroustrup --indent=spaces=2 \
  --pad-header --indent-labels --lineend=linux \
  --min-conditional-indent=0 --max-instatement-indent=80 \
  --keep-one-line-blocks --keep-one-line-statements \
  --align-pointer=name"
# --suffix=none 

## Option --align-reference=... is only available after version 2.02.
version=$(astyle --version 2>&1 \
  | sed 's/^[^0-9]*\([.0-9]*\).*/\1/;s/0*\([1-9][0-9]*\|0\)/\1/g')
major=$(echo "$version" | cut -d. -f1)
minor=$(echo "$version" | cut -d. -f2)
if test "$major" -gt 2 -o \( $major -eq 2 -a $minor -ge 2 \); then
  options="$options --align-reference=name"
fi
#echo >&2 "major --> $major"
#echo >&2 "minor --> $minor"
astyle $options "$@"

## No needs to remove spaces, astyle takes care of that; otherwise add:
## | sed -e 's/[ 	][ 	]*$//'

# Local Variables:
# mode: sh
# tab-width: 8
# indent-tabs-mode: nil
# fill-column: 78
# coding: utf-8
# End:
